name: Release

on:
  workflow_dispatch

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: lilypichu.scss
          destination: lilypichu.theme.cs

      - name: Add and Commit changes to pr-pages branch
        run: |
          git config --local user.email '41524896+PinkSerenity@users.noreply.github.com'
          git config --local user.name 'Pink Serenity'          
          git add lilypichu.theme.css --verbose
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
