name: Release

on:
  [workflow_dispatch, push]

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true
      
      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/LilyPichu/
      
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: stuff/overlay.scss
          destination: /tmp/LilyPichu/stuff/overlay.css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: lilypichu.scss
          destination: /tmp/LilyPichu/main.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: release
            fetch-depth: 1

      - name: Move CSS to destination Git branch
        run: |
          mv /tmp/LilyPichu/stuff/overlay.css ./stuff/overlay.css
          mv /tmp/LilyPichu/main.css ./main.css

      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
        
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Created release'
