name: Release

on:
  [workflow_dispatch, push]

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: lilypichu.scss
          destination: main.css

      - name: Add and Commit changes to pr-pages branch
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
        
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Created release'
