name: Update

on:
  workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Discord Class Updater
        # You may pin to the exact commit or the version.
        # uses: Metro420yt/class-update@8c8261c7586412f810b0018fe8dfde43942ff93f
        uses: Metro420yt/class-update@v1-rc
        with:
          folder: .
          ext: scss

      - name: Add and Commit changes
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'Update classes'
